DIR_WITH_DATA = './data'
OUTPUT_DIR = './output'
OUTPUT_EXTENTION = 'png'
THREADS = 6

THRESHOLD = 128
THRESHOLD_TOP = 255
THRESHOLD_BOTTOM = 0
POLYGONIZATION_METHOD = 'grid'

MIN_FILTER_AREA = 1500
MAX_FILTER_AREA = 100000


